
import java.awt.Color;
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EXCALIBUR
 */
public class Grafik extends javax.swing.JFrame {

 int x1, x2, y1, sayac1, sayac2, sayac3;
    public Grafik(int x1, int y1, int x2, int sayac1, int sayac2, int sayac3) {

     this.x1 = x1;
 this.x2 = x2;
 this.y1 = y1;
 
 this.sayac1=sayac1;
 this.sayac2=sayac2;
 this.sayac3=sayac3;
        initComponents();
    }

    public void paint(Graphics g) {
g.drawLine(50, 50, 50, 300);
 g.drawLine(50, 300, 400, 300);
 System.out.println( sayac1 + " " + sayac2 + " " + sayac3);
 g.setColor(Color.red);
 g.drawLine(100,sayac1+70, 100, 300);//sayfada görünmesi açısından +70 verilmiştir
 g.drawLine(200, sayac2+70, 200, 300);
 g.drawLine(300, sayac3+70, 300,300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    //</editor-fold>

    /* Create and display the form */
 /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafik().setVisible(true);
            }
        });
    } */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
